#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Bootstrapping my .dotfiles from '$BASEDIR'..."

### preparation ###
ln -sf "$BASEDIR/.zshenv" "$HOME"
source "$HOME/.zshenv"

### zsh ###
mkdir -p "$ZDOTDIR"
ln -sf "$BASEDIR/zsh/.zshenv" "$ZDOTDIR"
ln -sf "$BASEDIR/zsh/.zshrc" "$ZDOTDIR"
ln -sf "$BASEDIR/zsh/aliases" "$ZDOTDIR"
ln -sf "$BASEDIR/zsh/my_scripts.zsh" "$ZDOTDIR"
rm -rf "$HOME/.config/zsh/external"
ln -sf "$BASEDIR/zsh/external" "$ZDOTDIR"

### git ###
mkdir -p "$XDG_CONFIG_HOME/git"
ln -sf "$BASEDIR/git/config" "$XDG_CONFIG_HOME/git"
ln -sf "$BASEDIR/git/ignore" "$XDG_CONFIG_HOME/git"

### kitty ###
mkdir -p "$XDG_CONFIG_HOME/kitty"
ln -sf "$BASEDIR/kitty/kitty.conf" "$XDG_CONFIG_HOME/kitty"

### tmux ###
mkdir -p "$XDG_CONFIG_HOME/tmux"
ln -sf "$BASEDIR/tmux/tmux.conf" "$XDG_CONFIG_HOME/tmux"
mkdir -p "$XDG_CONFIG_HOME/tmuxp"
ln -sf "$BASEDIR/tmuxp/dotfiles.yml" "$XDG_CONFIG_HOME/tmuxp"

echo "Bootstrapping done, please RESTART YOUR TERMINAL and enjoy coding 🚀"

